routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::Resource('home/order', 'OrderController')->middleware('auth');
Route::Resource('home/orderItem', 'OrderItemController')->middleware('auth');
Route::Resource('home/product', 'ProductController')->middleware('auth');
Route::Resource('home/category', 'CategoryController')->middleware('auth');
Route::Resource('home/status', 'StatusController')->middleware('auth');

Route::get('home', 'HomeController@index')->name('home');

Route::get('login/{provider}', 'SocialController@redirect');
Route::get('login/{provider}/callback','SocialController@callback');


//Route::view('products', 'products.index',['products'=> 1]);
Route::get('city', 'CityController@index')->name('city');
Route::get('state', 'StateController@index')->name('state');
Route::get('country', 'CountryController@index')->name('country');

Route::resource('order', 'OrderController');

app/OrderItem.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class OrderItem extends Model
{
    protected $fillable = ['product_id','quantity','price','paid','discount'];

    public function order(){
        return $this->belongsTo(Order::class);
    }

    public function product(){
        return $this->belongsTo(Product::class);
    }
    
}

app/Http/Controllers/OrderItemController.php
<?php

namespace App\Http\Controllers;


use App\OrderItem;
use App\Order;
use Illuminate\Http\Request;

class OrderItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return OrderItem::all();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(OrderItem $orderItem)
    {
        return view('orderItem.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        dd($request);
        $validate = $request->validate([
            'quantity'      => 'required',
            'price'         => 'required',
            'discount'      => 'required',
            'paid'          => 'required',
        ]);

        $orderItem = new OrderItem();
        $orderItem->fill($validate);
        $orderItem->save();
        return $orderItem;
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\OrderItem  $orderItem
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        //dd($id);
        $itens = OrderItem::where(['order_id' => $id])->get();
        // dd($itens);
        
        return view('orderItem.edit',compact('itens'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\OrderItem  $orderItem
     * @return \Illuminate\Http\Response
     */
    public function edit(OrderItem $orderItem)
    {
        //
        dd($orderItem);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\OrderItem  $orderItem
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, OrderItem $orderItem)
    {
        
        $validate = $request->validate([
            'quantity'      => 'required',
            'price'         => 'required',
            'discount'      => 'required',
            'paid'          => 'required',
        ]);
        
        $orderItem->fill($validate);
        
        $orderItem->save();

        $itens = OrderItem::where(['order_id' => $orderItem->order_id])->get();
        
        
        return view('orderItem.edit',compact('itens'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\OrderItem  $orderItem
     * @return \Illuminate\Http\Response
     */
    public function destroy(OrderItem $orderItem)
    {
        if($orderItem->delete()){
            return $orderItem;
        }
        return false;
    }
}

resources/views/orderItem/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row" id="app">
        <front-page></font-page>
        <div class="col-md-12 offset-sm-2">
            <h1 class="display-3">Add a Order</h1>
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif

{{--                <div class="form-group">--}}
{{--                    <select title="Produts" class="selectpicker" id="selectProducts">--}}
{{--                    <option>Select...</option>--}}
{{--                   --}}
{{--                    </select>--}}
{{--                    <td>--}}
{{--                        <td>--}}
{{--                            <label for="quantity">Quantity</label>--}}
{{--                            <input type="number" name="quantity" id="quantity">--}}
{{--                        </td>--}}
{{--                        <td>--}}
{{--                            <a class="btn btn-primary" id="addProduct"">Add Product</a>--}}
{{--                        </td>--}}
{{--                    </td>--}}
{{--                </div>--}}

                <form method="post" class="form-group" action="{{ route('order.store') }}">
                    @csrf


                    <!-- <div class="form-group">
                        <label for="order">Order:</label>
                        <input type="number" class="form-control col-md-4" name="order" value="0"/>
                    </div> -->
                        
                    <div class="row form-group">
                        <div class="col-md-4">Product</div>
                        <div class="col-md-4">Quantity</div>
                        <div class="col-md-4">Price</div>
                    </div>
                    @foreach($products as $product)
                        <div class="input-group productItens" >
                            
                            <div class="input-group">
                                <input type="text" class="input-group-text col-md-4" value="{{$product->name}}" />
                                <input type="number" class="input-group-number col-md-4" name="quantity[{{$product->id}}]" value="0"/>
                                <div class="input-group-append col-md-2">
                                        <span class="input-group-text">R$</span>
                                        <span class="input-group-text">{{$product->price}}</span>
                                </div>
                                </div>
                                <input type="text" hidden="true" class="form-control sm-sm-3" name="product_id[{{$product->id}}]" value="{{$product->price}}"/>

                        </div>
                    @endforeach
                    <div class="form-group">

                        <label for="order">Order:</label>
                        <input type="number" class="form-control col-md-4" name="order" value="0"/>

                        <label for="discount"">Discount:</label>
                        <input type="number" class="form-control col-md-4" readonly name="discount" value="0"/>
                        <!-- <input type="number" hidden="true" class="input-group-text col-md-4" name="user_id" value=/> -->

                        <label for="observation">Observation:</label>
                        <input type="text" class="form-control" name="observation"/>

                        <label for="sendObservation">SendObservation:</label>
                        <input type="text" class="form-control" name="sendObservation"/>
                    </div>
                    <button type="submit" class="btn btn-primary">Add Order</button>
                </form>
            </div>
        </div>
    </div>



@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function() {
     
    });
</script>

@endsection

resources/views/orderItem/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row" id="app">
        <div class="col-md-12">
            <h1 class="display-3">Edit a Order {{$itens[0]->order_id}}</h1>
            
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif
                

                     <!-- <div class="form-group">
                        <label for="order">Order:</label>
                        <input type="number" class="form-control col-md-4" name="order" value="0"/>
                    </div> 
                          -->
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-1">Item</div>
                            <div class="col-sm-2">Product</div>
                            <div class="col-sm-2">Quantity</div>
                            <div class="col-sm-2">Discount</div>
                            <div class="col-sm-2">Price</div>
                            <div class="col-sm-1">Paid</div>                            
                            <div class="col-sm-2">Acao</div>
                        </div>
                    
                        @foreach ($itens as $item)

                        <div class="row-inline">
                            <form method="POST" class="form-inline" action="{{ route('orderItem.update', $item->id) }}">
                                @csrf
                                @method('PATCH')
                                <div class="col-sm-1">
                                    {{$item->id}}
                                </div>
                                <div class="col-sm-2">
                                    <input type="hidden" class="col" name="product_id" value="{{$item->product->id}}"/>
                                    {{$item->product->name}}
                                </div>
                                <div class="col-sm-2">
                                    <input type="text" class="col" name="quantity" value="{{$item->quantity}}"/>
                                </div>
                                <div class="col-sm-2">
                                    <input type="text" class="col" name="discount" value="{{$item->discount}}"/>
                                </div>
                                <div class="col-sm-2">
                                    <input type="text" class="col" name="price" value="{{$item->price}}"/>
                                </div>
                                <div class="col-sm-1">
                                    <input type="text" class="col" name="paid" value="{{$item->paid}}"/>
                                </div>
                                <div class="col-sm-2">
                                    <button type="submit" class="btn btn-sm btn-primary">Add Order</button>
                                </div>
                            </form>
                        </div>
                                
                        
                        @endforeach
                    </div>
            </div>
        </div>
    </div>



@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function() {
        

    });
</script>

@endsection

resources/views/orderItem/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-12">

            @if(session()->get('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div>
            @endif
        </div>
        <div class="col-sm-12">
            <div class="float-rigth">
                  <a href="{{ route('order.create') }}" class="btn btn-primary float-right">New Order</a>
              </div>
        </div>      
        <div class="col-sm-12">'
            <h1 class="display-3 float-left">Orders</h1>
            <table class="table table-striped">
                <thead class="table table-dark">
                <tr>
                    <td>id</td>
                    <td>code</td>
                   <td>discount</td>
                   <td>observation</td>
{{--                    <td>City</td>--}}
{{--                    <td>Country</td>--}}
                    <td colspan = 3>Actions</td>
                </tr>
                </thead>
                <tbody>

                @foreach($orders as $order)
                    <tr>
                        <td>{{$order->id}}</td>
                        <td>{{$order->code}}</td>
                       <td>{{$order->discount}}</td>
                       <td>{{$order->observation}}</td>
{{--                        <td>{{$product->city}}</td>--}}
{{--                        <td>{{$product->country}}</td>--}}
{{--                        <td{{$product->country}}</td>--}}
                        <td>
                            <a href="{{ route('order.edit',$order->id)}}" class="btn btn-primary">Edit</a>
                        </td>
                        <td>
                            <a href="{{ route('order.show',$order->id)}}" class="btn btn-primary">Show</a>
                        </td>

                        <td>
                            <form action="{{ route('order.destroy', $order->id)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/orderItem/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row" id="app">
        <front-page></font-page>
        <div class="col-md-12 offset-sm-2">
            <h1 class="display-3">Edit a Order</h1>
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif

                <form method="post" class="form-group" action="{{ route('order.store') }}">
                    @csrf


                    <!-- <div class="form-group">
                        <label for="order">Order:</label>
                        <input type="number" class="form-control col-md-4" name="order" value="0"/>
                    </div> -->
                        
                   <div class="row form-group">
                        <div class="col-md-4">Product</div>
                        <div class="col-md-4">Quantity</div>
                        <div class="col-md-4">Price</div>
                    </div>
                   
                    @dump($orders)

                    <div class="form-group">

                        <label for="order">Order:</label>
                        <input type="number" class="form-control col-md-4" name="order" value=""/>

                        <label for="discount"">Discount:</label>
                        <input type="number" class="form-control col-md-4" readonly name="discount" value="0"/>
                        <!-- <input type="number" hidden="true" class="input-group-text col-md-4" name="user_id" value=/> -->

                        <label for="observation">Observation:</label>
                        <input type="text" class="form-control" name="observation"/>

                        <label for="sendObservation">SendObservation:</label>
                        <input type="text" class="form-control" name="sendObservation"/>
                    </div>
                    <button type="submit" class="btn btn-primary">Add Order</button>
                </form>
            </div>
        </div>
    </div>



@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function() {
      

    });
</script>

@endsection