routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::Resource('home/order', 'OrderController')->middleware('auth');
Route::Resource('home/orderItem', 'OrderItemController')->middleware('auth');
Route::Resource('home/product', 'ProductController')->middleware('auth');
Route::Resource('home/category', 'CategoryController')->middleware('auth');
Route::Resource('home/status', 'StatusController')->middleware('auth');

Route::get('home', 'HomeController@index')->name('home');

Route::get('login/{provider}', 'SocialController@redirect');
Route::get('login/{provider}/callback','SocialController@callback');


//Route::view('products', 'products.index',['products'=> 1]);
Route::get('city', 'CityController@index')->name('city');
Route::get('state', 'StateController@index')->name('state');
Route::get('country', 'CountryController@index')->name('country');

Route::resource('order', 'OrderController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'code','name','description','price', 'netWeight','weight','height','width','depth', 'exclusive', 'gtin', 'factorScore', 'isService', 'bonus' , 'active'
    ];

    public function category()
    {
        return $this->belongsToMany(Category::class);
    }

    public function status()
    {
        return $this->hasMany(Status::class);
    }

    // public function order()
    // {
    //     return $this->belongsTo(Order::class);
    // }

    // public function productItem()
    // {
    //     return $this->belongsToMany(ProductItem::class);
    // }

   public function orderItem()
   {
       return $this->belongsTo(OrderItem::class);
   }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function index()
    {
        $products =  Product::with('category')->get();
//        dd($products[0]->category[0]->id);
        return view('products.index', compact('products',$products));
    }


    public function edit(Product $product)
    {
        $product::with('categories');
        $categories = Category::all();
        return view('products.edit', compact(['product','categories']));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Product
     */

    public function store(Request $request)
    {
        $validate = $request->validate([
            'name'        => 'required|string|min:5',
            'description'       => 'required|min:20',
            'price'       => 'required|min:3',
            'categories'  => 'required',
        ]);

        $product = new Product();
        $product->fill($validate);
        $product->save();
        $product->category()->sync($validate['categories']);
        $product->status()->sync($validate['status']);
        return $product;
    }

    /**
     * Display the specified resource.
     *
     * @param  Product  $product
     * @return Product
     */


    public function show(Product $product)
    {
        return $product;
    }


    public function update(Request $request ,Product $product)
    {

        $validate = $request->validate([
            'name'        => 'required|string|min:5',
            'description' => 'required|min:20',
            'price'       => 'required|min:3',
            'active'  => 'required',
            'categories' => 'required' ,

        ]);

        $product->fill($validate);
        $product->save();
        $product->category()->sync($validate['categories']);
//        $product->status()->sync($validate['status']);

//        return $product;
        return redirect('/home/product')->with('success', 'Product updated!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Product $product
     * @return Product
     * @throws \Exception
     * @throws \Exception
     */


    public function destroy(Product $product)
    {
        if($product->delete()){
            return redirect('/home/product')->with('success', 'Product deleted!');
        }
        return redirect('/home/status')->with('fail', 'Product not deleted!');

    }
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-8 offset-sm-2">
            <h1 class="display-3">Add a Product</h1>
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif
                <form method="post" action="{{ route('product.store') }}">
                    @csrf
                    <div class="form-group">
                        <label for="first_name">First Name:</label>
                        <input type="text" class="form-control" name="first_name"/>
                    </div>

                    <div class="form-group">
                        <label for="last_name">Last Name:</label>
                        <input type="text" class="form-control" name="last_name"/>
                    </div>

                    <div class="form-group">
                        <label for="email">Email:</label>
                        <input type="text" class="form-control" name="email"/>
                    </div>
                    <div class="form-group">
                        <label for="city">City:</label>
                        <input type="text" class="form-control" name="city"/>
                    </div>
                    <div class="form-group">
                        <label for="country">Country:</label>
                        <input type="text" class="form-control" name="country"/>
                    </div>
                    <div class="form-group">
                        <label for="job_title">Job Title:</label>
                        <input type="text" class="form-control" name="job_title"/>
                    </div>
                    <button type="submit" class="btn btn-primary">Add contact</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h4 class="display-3">Update a Product</h4>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            <br />
        @endif

        <form method="post" action="{{ route('product.update', $product->id) }}">
            @method('PATCH')
            @csrf
{{--            <div class="form-group">--}}
{{--                <label for="first_name">ID:</label>--}}
{{--                <input type="text" class="form-control" name="id" value="{{ $product->id }}" />--}}
{{--            </div>--}}

            <div class="form-group">
                <label for="last_name">Name:</label>
                <input type="text" class="form-control" name="name" value="{{ $product->name }}" />
            </div>

            <div class="form-group">
                <label for="email">Code:</label>
                <input type="number" class="form-control" name="code" value="{{ $product->code }}" />
            </div>

            <div class="form-group">
                <label for="description">Description:</label>
                <input type="text" class="form-control" name="description" value="{{ $product->description }}" />
            </div>

            <div class="form-group">
                <label for="city">Price:</label>
                <input type="number" class="form-control" name="price" value="{{ $product->price }}" />
            </div>
            <div class="form-group">
                <label for="country">Active:</label>
                <input type="text" class="form-control" name="active" value="{{ $product->active }}" />
            </div>

            <div class="form-group">
                <label for="categories">Category:</label>
                <select class="form-control" name="categories">
                    <option name="categories" value=""></option>
                    @foreach($categories as $category)
                        <option value="{{ $category->id }}"
                            @if( isset($product->category[0]) and $category->id === $product->category[0]->id)
                                selected
                            @endif
                        >
                            {{ $category->name }}
                        </option>
                    @endforeach
                </select>
            </div>
{{--            <div class="form-group">--}}
{{--                <label for="job_title">Job Title:</label>--}}
{{--                <input type="text" class="form-control" name="categories" value="{{ $product->categories }}" />--}}
{{--            </div>--}}
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-12">

            @if(session()->get('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div>
            @endif
        </div>
        <div class="col-sm-12">
            <h1 class="display-3">Products</h1>
            <table class="table table-striped">
                <thead class="table table-dark">
                <tr>
                    <td>id</td>
                    <td>code -- name</td>
                    <td>description</td>
                    <td>price</td>
                    <td>category</td>
                    <td>active</td>
                    <td colspan = 2>Actions</td>
                </tr>
                </thead>
                <tbody>

                @foreach($products as $product)
                    <tr>
{{--                        {{$product}}--}}
{{--                        'code','name','description','price', 'netWeight','weight','height','width','depth', 'exclusive', 'gtin', 'factorScore', 'isService', 'bonus' , 'active'--}}
                        <td>{{$product->id}}</td>
                        <td>{{$product->code}} -- {{$product->name}}</td>
                        <td>{{$product->description}}</td>
                        <td>R$ {{number_format( $product->price ,2,',','.') }}</td>
                        <td>{{ $product->category->first()->name ?? "" }}</td>
                        <td>
                            @if($product->active === 1)
                                Ativo
                            @else
                                Inativo
                            @endif
                        </td>
                        <td>
                            <a href="{{ route('product.edit',$product->id)}}" class="btn btn-primary">Edit</a>
                        </td>
                        <td>
                            <form action="{{ route('product.destroy', $product->id)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection