routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::Resource('home/order', 'OrderController')->middleware('auth');
Route::Resource('home/orderItem', 'OrderItemController')->middleware('auth');
Route::Resource('home/product', 'ProductController')->middleware('auth');
Route::Resource('home/category', 'CategoryController')->middleware('auth');
Route::Resource('home/status', 'StatusController')->middleware('auth');

Route::get('home', 'HomeController@index')->name('home');

Route::get('login/{provider}', 'SocialController@redirect');
Route::get('login/{provider}/callback','SocialController@callback');


//Route::view('products', 'products.index',['products'=> 1]);
Route::get('city', 'CityController@index')->name('city');
Route::get('state', 'StateController@index')->name('state');
Route::get('country', 'CountryController@index')->name('country');

Route::resource('order', 'OrderController');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{

    protected $fillable = ['order','user_id','discount','observation','sendObservation'];

    public function address(){
        return $this->hasOne(Address::class);
    }

    public function payment(){
        return $this->hasMany(Payment::class);
    }

    public function orderItem(){
        return $this->hasMany(OrderItem::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

//    public function OrderItem(){return $this->belongsToMany(OrderItem::class);}
//    public function shipment(){}
//    public function traking(){}
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Order;
use App\OrderItem;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Product;
use Illuminate\Support\Arr;
use Illuminate\View\View;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return view
     */
    public function index() : View
    {
        $orders =  Order::with('orderItem.product')->where(['user_id' => Auth::id()])->get();
        return view('order.index', compact('orders'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Order $order) :View
    {
        $products =  Product::with('category')->get();
        // dd($products);
        return view('order.create', compact('products'));
        // return view('order.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function store(User $user,Request $request)
    {
        dump($user);exit;
        $request['user_id'] = Auth::user()->id;
        $validateOrder = $request->validate([
            'order' => 'required',
            'user_id' => $user->id,
            'quantity'         => 'required|array',
            'product_id'   => 'required|array',
            'sendObservation'   => 'max:250',
            'observation'   => 'max:250',
        ]);

        $itens = Arr::pull($request, 'quantity');
        $discount = Arr::pull($request, 'discount');
        $products = Arr::pull($request, 'product_id');


        // $validateOrder['idUser'] = Auth::user()->id;

        $order = new Order();
        $order->fill($validateOrder);
        $order->save();

        // dd($itens);
        // array:3 [
        //     1 => "11"
        //     2 => "33"
        //     3 => "22"
        // ]


        foreach($itens as $product_id => $quantity){
            $orderItem = new OrderItem();

            $item = [
                'order_id'    =>  $order->id,
                'product_id'    => $product_id,
                'quantity'    => $quantity,
                'price'    => $products[$product_id],
                'discount'         => $discount,
            ];
            $orderItems[] = $item;

            $orderItem->fill($item);
            $orderItem->save();


        }

        // return view('order.index');
        $orders =  Order::with('orderItem.product')->where(['user_id' => Auth::id()])->get();
        return view('order.index', compact('orders'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\order  $order
     * @return View
     */
    public function show(Order $order) :view
    {
        $orders =  Order::with('orderItem')->where(['user_id' => Auth::id()])->get();
        return view('order.show', compact('orders'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        $validate = $request->validate([
            'order_id'      => 'required',
            'product_id'    => 'required',
            'quantity'      => 'required|number|min:0',
            'price'         => 'required',
        ]);

        // $order = new order();
        $order->fill($validate);
        $order->save();
        return $order;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        if($order->delete()){
            return $order;
        }
        return false;
    }
}

resources/views/order/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row" id="app">
        <front-page></font-page>
        <div class="col-md-12 offset-sm-2">
            <h1 class="display-3">Add a Order</h1>
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif

{{--                <div class="form-group">--}}
{{--                    <select title="Produts" class="selectpicker" id="selectProducts">--}}
{{--                    <option>Select...</option>--}}
{{--                   --}}
{{--                    </select>--}}
{{--                    <td>--}}
{{--                        <td>--}}
{{--                            <label for="quantity">Quantity</label>--}}
{{--                            <input type="number" name="quantity" id="quantity">--}}
{{--                        </td>--}}
{{--                        <td>--}}
{{--                            <a class="btn btn-primary" id="addProduct"">Add Product</a>--}}
{{--                        </td>--}}
{{--                    </td>--}}
{{--                </div>--}}

                <form method="post" class="form-group" action="{{ route('order.store') }}">
                    @csrf


                    <!-- <div class="form-group">
                        <label for="order">Order:</label>
                        <input type="number" class="form-control col-md-4" name="order" value="0"/>
                    </div> -->
                        
                    <div class="row form-group">
                        <div class="col-md-4">Product</div>
                        <div class="col-md-4">Quantity</div>
                        <div class="col-md-4">Price</div>
                    </div>
                    @foreach($products as $product)
                        <div class="input-group productItens" >
                            
                            <div class="input-group">
                                <input type="text" class="input-group-text col-md-4" value="{{$product->name}}" />
                                <input type="number" class="input-group-number col-md-4" name="quantity[{{$product->id}}]" value="0"/>
                                <div class="input-group-append col-md-2">
                                        <span class="input-group-text">R$</span>
                                        <span class="input-group-text">{{$product->price}}</span>
                                </div>
                                </div>
                                <input type="text" hidden="true" class="form-control sm-sm-3" name="product_id[{{$product->id}}]" value="{{$product->price}}"/>

                        </div>
                    @endforeach
                    <div class="form-group">

                        <label for="order">Order:</label>
                        <input type="number" class="form-control col-md-4" name="order" value="0"/>

                        <label for="discount"">Discount:</label>
                        <input type="number" class="form-control col-md-4" readonly name="discount" value="0"/>
                        <!-- <input type="number" hidden="true" class="input-group-text col-md-4" name="user_id" value=/> -->

                        <label for="observation">Observation:</label>
                        <input type="text" class="form-control" name="observation"/>

                        <label for="sendObservation">SendObservation:</label>
                        <input type="text" class="form-control" name="sendObservation"/>
                    </div>
                    <button type="submit" class="btn btn-primary">Add Order</button>
                </form>
            </div>
        </div>
    </div>



@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function() {
        $("#addProduct").click(function (){
            var product = $("#selectProducts option").filter(':selected');
            var nameProduct = product.text();
            var idProduct = product.val();
            var quantity = $("#quantity").val();
            inputProduct = $("#productName").clone();
            inputProduct2 = $("#productName").clone();
            inputQuantity = $("#productQuantity").clone().removeAttr("hidden");

            $(".productItens").append(inputProduct2.val(idProduct));
            $(".productItens").append(inputProduct.removeAttr("hidden").val(nameProduct));
            $(".productItens").append(inputQuantity.val(quantity));

        });

    });
</script>

@endsection

resources/views/order/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row" id="app">
        <front-page></font-page>
        <div class="col-md-12 offset-sm-2">
            <h1 class="display-3">Edit a Order</h1>
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif

                <form method="post" class="form-group" action="{{ route('order.store') }}">
                    @csrf


                    <!-- <div class="form-group">
                        <label for="order">Order:</label>
                        <input type="number" class="form-control col-md-4" name="order" value="0"/>
                    </div> -->
                        
                    
                    <div class="row form-group">
                        <div class="col-md-4">Product</div>
                        <div class="col-md-4">Quantity</div>
                        <div class="col-md-4">Price</div>
                    </div>
                   
                    {{$order}}

                    <div class="form-group">

                        <label for="order">Order:</label>
                        <input type="number" class="form-control col-md-4" name="order" value=""/>

                        <label for="discount"">Discount:</label>
                        <input type="number" class="form-control col-md-4" readonly name="discount" value="0"/>
                        <!-- <input type="number" hidden="true" class="input-group-text col-md-4" name="user_id" value=/> -->

                        <label for="observation">Observation:</label>
                        <input type="text" class="form-control" name="observation"/>

                        <label for="sendObservation">SendObservation:</label>
                        <input type="text" class="form-control" name="sendObservation"/>
                    </div>
                    <button type="submit" class="btn btn-primary">Add Order</button>
                </form>
            </div>
        </div>
    </div>



@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function() {
       

    });
</script>

@endsection

resources/views/order/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-12">

            @if(session()->get('success'))
                <div class="alert alert-success">
                    {{ session()->get('success') }}
                </div>
            @endif
        </div>
        <div class="col-sm-12">
            <div class="float-rigth">
                  <a href="{{ route('order.create') }}" class="btn btn-primary float-right">New Order</a>
              </div>
        </div>      
        <div class="col-sm-12">'
            <h1 class="display-3 float-left">Orders</h1>
            <table class="table table-striped">
                <thead class="table table-dark">
                <tr>
                    <td>id</td>
                    <td>code</td>
                   <td>discount</td>
                   <td>observation</td>
{{--                    <td>City</td>--}}
{{--                    <td>Country</td>--}}
                    <td colspan = 3>Actions</td>
                </tr>
                </thead>
                <tbody>

                @foreach($orders as $order)
                    <tr>
                        <td>{{$order->id}}</td>
                        <td>{{$order->code}}</td>
                       <td>{{$order->discount}}</td>
                       <td>{{$order->observation}}</td>
{{--                        <td>{{$product->city}}</td>--}}
{{--                        <td>{{$product->country}}</td>--}}
{{--                        <td{{$product->country}}</td>--}}
                        <td>
                            <a href="{{ route('order.edit',$order->id)}}" class="btn btn-primary">Edit</a>
                        </td>
                        <td>
                            <a href="{{ route('orderItem.show',$order->id)}}" class="btn btn-primary">Show</a>
                        </td>

                        <td>
                            <form action="{{ route('order.destroy', $order->id)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/order/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row" id="app">
        <front-page></font-page>
        <div class="col-md-12 offset-sm-2">
            <h1 class="display-3">Edit a Order</h1>
            <div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                @endif

                <form method="post" class="form-group" action="{{ route('order.store') }}">
                    @csrf


                    <!-- <div class="form-group">
                        <label for="order">Order:</label>
                        <input type="number" class="form-control col-md-4" name="order" value="0"/>
                    </div> -->
                        
                   <div class="row form-group">
                        <div class="col-md-4">Product</div>
                        <div class="col-md-4">Quantity</div>
                        <div class="col-md-4">Price</div>
                    </div>
                   
                    @dump($orders)

                    <div class="form-group">

                        <label for="order">Order:</label>
                        <input type="number" class="form-control col-md-4" name="order" value=""/>

                        <label for="discount"">Discount:</label>
                        <input type="number" class="form-control col-md-4" readonly name="discount" value="0"/>
                        <!-- <input type="number" hidden="true" class="input-group-text col-md-4" name="user_id" value=/> -->

                        <label for="observation">Observation:</label>
                        <input type="text" class="form-control" name="observation"/>

                        <label for="sendObservation">SendObservation:</label>
                        <input type="text" class="form-control" name="sendObservation"/>
                    </div>
                    <button type="submit" class="btn btn-primary">Add Order</button>
                </form>
            </div>
        </div>
    </div>



@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function() {
       
    });
</script>

@endsection